apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  version: 8.4.3
  nodeSets:
  - name: master
    count: 3
    config:
      node.roles: ["master"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: ssd-sc
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']      
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 1Gi
          env:
          - name: JAVA_OPTS
            value: -Xms2g -Xmx2g
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "dedicated"
                      operator: In
                      values:
                        - "elasticsearch"
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "elasticsearch"
            effect: "NoSchedule"
  - name: data
    count: 3
    config:
      node.roles: ["data", "ingest"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: ssd-sc
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 4Gi
          env:
          - name: JAVA_OPTS
            value: -Xms2g -Xmx2g
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "dedicated"
                      operator: In
                      values:
                        - "elasticsearch"
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "elasticsearch"
            effect: "NoSchedule"
